"use client";

import { useState } from "react";
import { Header } from "@/components/dashboard/Header";
import { PineScriptEditor } from "@/components/editor/PineScriptEditor";

const DEFAULT_CODE = `//@version=5
strategy("My Strategy", overlay=true)

// Inputs
length = input.int(14, "RSI Length", minval=1)
overbought = input.int(70, "Overbought Level")
oversold = input.int(30, "Oversold Level")

// Calculate RSI
rsiValue = ta.rsi(close, length)

// Entry conditions
longCondition = ta.crossover(rsiValue, oversold)
shortCondition = ta.crossunder(rsiValue, overbought)

// Execute trades
if longCondition
    strategy.entry("Long", strategy.long)
if shortCondition
    strategy.entry("Short", strategy.short)

// Plot
plot(rsiValue, "RSI", color.purple)
hline(overbought, "Overbought", color.red)
hline(oversold, "Oversold", color.green)
`;

export default function CodePage() {
  const [code, setCode] = useState(DEFAULT_CODE);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = async (description: string) => {
    setIsGenerating(true);
    // Simulate API call - in production this would call the backend
    await new Promise((resolve) => setTimeout(resolve, 2000));

    // Mock generated code
    const generatedCode = `//@version=5
strategy("${description}", overlay=true)

// Generated by OpenQuant AI
// Description: ${description}

// Inputs
length = input.int(14, "Period", minval=1)

// Calculate indicator
value = ta.sma(close, length)

// Entry conditions
longCondition = ta.crossover(close, value)
shortCondition = ta.crossunder(close, value)

// Execute trades
if longCondition
    strategy.entry("Long", strategy.long)
if shortCondition
    strategy.entry("Short", strategy.short)

// Plot
plot(value, "Signal", color.purple)
`;
    setCode(generatedCode);
    setIsGenerating(false);
  };

  return (
    <div className="flex flex-col h-full">
      <Header
        title="Pine Script Generator"
        subtitle="Describe your strategy in natural language"
      />
      <div className="flex-1 p-6">
        <div className="h-full bg-background-card rounded-lg border border-border-primary overflow-hidden">
          <PineScriptEditor
            value={code}
            onChange={setCode}
            onGenerate={handleGenerate}
            isGenerating={isGenerating}
          />
        </div>
      </div>
    </div>
  );
}
