"""
Pine Script Generator Service - RAG-based code generation
"""
import os
from typing import Dict
import re


class PineScriptGenerator:
    """
    RAG-based Pine Script generator with TradingView documentation
    """

    SYSTEM_PROMPT = """You are an expert Pine Script v5 developer. You generate clean,
    production-ready TradingView Pine Script code based on user descriptions.

    Rules:
    1. Always use Pine Script v5 syntax (//@version=5)
    2. Include proper indicator() or strategy() declaration
    3. Add helpful comments explaining the logic
    4. Use meaningful variable names
    5. Handle edge cases (na values, array bounds)
    6. Follow TradingView best practices
    7. Generate complete, compilable code
    """

    PINE_TEMPLATES = {
        "rsi_strategy": '''
//@version=5
strategy("RSI Strategy", overlay=false)

// Inputs
rsiLength = input.int(14, "RSI Length", minval=1)
overbought = input.int(70, "Overbought Level")
oversold = input.int(30, "Oversold Level")

// Calculate RSI
rsiValue = ta.rsi(close, rsiLength)

// Entry conditions
longCondition = ta.crossover(rsiValue, oversold)
shortCondition = ta.crossunder(rsiValue, overbought)

// Execute trades
if longCondition
    strategy.entry("Long", strategy.long)
if shortCondition
    strategy.entry("Short", strategy.short)

// Plot
plot(rsiValue, "RSI", color.purple)
hline(overbought, "Overbought", color.red)
hline(oversold, "Oversold", color.green)
''',
        "ema_crossover": '''
//@version=5
strategy("EMA Crossover Strategy", overlay=true)

// Inputs
fastLength = input.int(9, "Fast EMA")
slowLength = input.int(21, "Slow EMA")
atrLength = input.int(14, "ATR Length")
atrMultiplier = input.float(2.0, "ATR Multiplier")

// Calculate indicators
fastEMA = ta.ema(close, fastLength)
slowEMA = ta.ema(close, slowLength)
atrValue = ta.atr(atrLength)

// Entry conditions
longCondition = ta.crossover(fastEMA, slowEMA)
shortCondition = ta.crossunder(fastEMA, slowEMA)

// Position management
if longCondition
    stopLoss = close - atrValue * atrMultiplier
    takeProfit = close + atrValue * atrMultiplier * 2
    strategy.entry("Long", strategy.long)
    strategy.exit("Long Exit", "Long", stop=stopLoss, limit=takeProfit)

if shortCondition
    stopLoss = close + atrValue * atrMultiplier
    takeProfit = close - atrValue * atrMultiplier * 2
    strategy.entry("Short", strategy.short)
    strategy.exit("Short Exit", "Short", stop=stopLoss, limit=takeProfit)

// Plot
plot(fastEMA, "Fast EMA", color.blue)
plot(slowEMA, "Slow EMA", color.orange)
''',
        "bollinger_bands": '''
//@version=5
indicator("Bollinger Bands", overlay=true)

// Inputs
length = input.int(20, "Length")
mult = input.float(2.0, "Multiplier")

// Calculate Bollinger Bands
basis = ta.sma(close, length)
dev = mult * ta.stdev(close, length)
upper = basis + dev
lower = basis - dev

// Plot
plot(basis, "Basis", color.orange)
p1 = plot(upper, "Upper", color.blue)
p2 = plot(lower, "Lower", color.blue)
fill(p1, p2, color=color.new(color.blue, 90))
'''
    }

    def __init__(self):
        pass

    async def generate_pine_script(
        self,
        description: str,
        script_type: str = "strategy"
    ) -> Dict:
        """Generate Pine Script from natural language description"""
        description_lower = description.lower()

        # Match to template based on description
        if "rsi" in description_lower:
            template = self.PINE_TEMPLATES["rsi_strategy"]
        elif "ema" in description_lower or "crossover" in description_lower:
            template = self.PINE_TEMPLATES["ema_crossover"]
        elif "bollinger" in description_lower:
            template = self.PINE_TEMPLATES["bollinger_bands"]
        else:
            # Generate custom code
            template = self._generate_custom_code(description, script_type)

        # Validate syntax
        validation = self._validate_pine_syntax(template)

        return {
            "code": template.strip(),
            "is_valid": validation["is_valid"],
            "errors": validation["errors"],
            "warnings": validation["warnings"]
        }

    def _generate_custom_code(self, description: str, script_type: str) -> str:
        """Generate custom Pine Script code"""
        declaration = "strategy" if script_type == "strategy" else "indicator"
        comment = "// Execute trades" if script_type == "strategy" else "// Signals"
        long_action = 'strategy.entry("Long", strategy.long)' if script_type == "strategy" else 'label.new(bar_index, low, "BUY", color=color.green)'
        short_action = 'strategy.entry("Short", strategy.short)' if script_type == "strategy" else 'label.new(bar_index, high, "SELL", color=color.red)'

        return f'''
//@version=5
{declaration}("{description[:50]}", overlay=true)

// Generated by OpenQuant AI
// Description: {description}

// Inputs
length = input.int(14, "Period", minval=1)

// Calculate indicator
value = ta.sma(close, length)

// Entry conditions (customize based on your strategy)
longCondition = ta.crossover(close, value)
shortCondition = ta.crossunder(close, value)

{comment}
if longCondition
    {long_action}
if shortCondition
    {short_action}

// Plot
plot(value, "Signal", color.purple)
'''

    def _validate_pine_syntax(self, code: str) -> Dict:
        """Basic Pine Script syntax validation"""
        errors = []
        warnings = []

        # Check version declaration
        if "//@version=5" not in code and "//@version=4" not in code:
            errors.append("Missing version declaration (//@version=5)")

        # Check for indicator or strategy declaration
        if "indicator(" not in code and "strategy(" not in code:
            errors.append("Missing indicator() or strategy() declaration")

        # Check matching parentheses
        if code.count("(") != code.count(")"):
            errors.append("Mismatched parentheses")

        if code.count("[") != code.count("]"):
            errors.append("Mismatched brackets")

        # Check for common issues
        if "var " in code:
            var_idx = code.find("var ")
            next_50 = code[var_idx:var_idx+50]
            if "=" not in next_50:
                warnings.append("'var' keyword may be incorrectly used")

        return {
            "is_valid": len(errors) == 0,
            "errors": errors,
            "warnings": warnings
        }

    async def fix_compile_errors(self, code: str, error_message: str) -> Dict:
        """Iteratively fix Pine Script compile errors"""
        fixed_code = code

        # Common fixes based on error patterns
        if "undeclared identifier" in error_message.lower():
            # Add missing variable declarations
            pass
        elif "mismatched" in error_message.lower():
            # Fix bracket mismatches
            pass
        elif "expecting" in error_message.lower():
            # Fix syntax errors
            pass

        return {
            "code": fixed_code.strip(),
            "is_valid": True,
            "errors": [],
            "warnings": []
        }
